[package]
name = "f06"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3"
nalgebra = { version = "0.32.3", features = ["serde", "sparse"] }
serde = { version = "1.0", features = ["derive"] }
