[package]
name = "f06"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3"
num = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }

[dependencies.nalgebra]
version = "0.32.3"
features = ["serde", "serde-serialize", "sparse"]
