# build rust releases

on:
  release:
    types: [created]

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
          archive: zip
          - target: x86_64-unknown-linux-musl
          archive: zip
          - target: x86_64-apple-darwin
          archive: zip
    steps:
      - uses: actions/checkout@master
      - name: Compile and release f06info
        uses: rust-build/rust-build.action@v1.4.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SRC_DIR: f06info
          ARCHIVE_NAME: f06info-${{ github.event.release.tag_name  }}-${{ matrix.target }}.zip
        with:
          RUSTTARGET: ${{ matrix.target }}
          ARCHIVE_TYPES: ${{ matrix.archive }}
      - name: Compile and release f06csv
        uses: rust-build/rust-build.action@v1.4.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SRC_DIR: f06csv
          ARCHIVE_NAME: f06csv-${{ github.event.release.tag_name  }}-${{ matrix.target }}.zip
        with:
          RUSTTARGET: ${{ matrix.target }}
          ARCHIVE_TYPES: ${{ matrix.archive }}
      - name: Compile and release f06diff
        uses: rust-build/rust-build.action@v1.4.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SRC_DIR: f06diff
          ARCHIVE_NAME: f06diff-${{ github.event.release.tag_name  }}-${{ matrix.target }}.zip
        with:
          RUSTTARGET: ${{ matrix.target }}
          ARCHIVE_TYPES: ${{ matrix.archive }}
